apiVersion: v1
kind: Secret
metadata:
  name: follow-service-secret
type: Opaque
data:
  MYSQL_DATASOURCE: amRiYzpteXNxbDovL2ZvbGxvdy1zZXJ2aWNlLWRiOjMzMDYvZm9sbG93X3NlcnZpY2U=
  MYSQL_USER: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  RABBITMQ_USERNAME: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=