apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow-service
  labels:
    app: follow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follow-service
  template:
    metadata:
      labels:
        app: follow-service
    spec:
      containers:
        - name: follow-service
          image: bwildeman/kwetter_followerservice:latest
          ports:
            - containerPort: 9002
          envFrom:
            - configMapRef:
                name: follow-service-config
            - secretRef:
                name: follow-service-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"